# Generated by Django 2.2.5 on 2019-11-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswers',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_text', models.CharField(max_length=1000)),
                ('is_correct', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_title', models.CharField(max_length=50)),
                ('num_questions', models.IntegerField()),
                ('grade_level', models.IntegerField()),
            ],
        ),
    ]
