# Generated by Django 2.2.5 on 2019-11-12 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeachTool', '0002_auto_20191112_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='quiz_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TeachTool.Quiz'),
        ),
    ]
