# Generated by Django 2.2.5 on 2019-11-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeachTool', '0004_quizanswer_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='summary',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
