# Generated by Django 2.2.5 on 2019-12-06 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeachTool', '0006_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResults',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('quiz_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TeachTool.Quiz')),
                ('student_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TeachTool.Student')),
            ],
        ),
    ]
