# Generated by Django 2.2.5 on 2019-12-07 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeachTool', '0007_quizresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('student_answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_answer', models.CharField(max_length=1000)),
                ('correct_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeachTool.QuizAnswer')),
                ('question', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TeachTool.QuizQuestion')),
                ('student_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TeachTool.Student')),
            ],
        ),
    ]
