# Generated by Django 2.2.5 on 2019-12-07 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeachTool', '0008_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='attempt_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='quiz_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TeachTool.Quiz'),
        ),
    ]
