# Generated by Django 2.2.5 on 2019-12-07 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeachTool', '0010_auto_20191207_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='quiz_id',
        ),
    ]
