# Generated by Django 2.2.5 on 2019-12-07 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeachTool', '0011_remove_studentanswer_quiz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='quiz_id',
            field=models.ForeignKey(default=84, on_delete=django.db.models.deletion.CASCADE, to='TeachTool.Quiz'),
        ),
    ]
