# Generated by Django 2.2.5 on 2019-12-08 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeachTool', '0012_studentanswer_quiz_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='attempt_num',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='quiz_id',
        ),
    ]
